### ISSUE TITLE
UI doesn't work / is garbled.

### ISSUE THREAD

**Issue by Cosmic-Goat** [iondodon/i3-switcher-x11#1]
This is a wonderful idea, thank you for making it!

I copied the binary out of the .deb package just to try running it since I'm on Arch (I also had to install `scrot` - perhaps this could be listed in the readme?).

The functionality works, however this is what it displays:
![image](https://github.com/iondodon/i3-switcher-x11/assets/13304815/3a1235cc-cab8-4b39-9e3e-120012534848)

I have two monitors if that is an issue.

Interestingly it seems to display fine if I don't have `scrot` installed (without images of course, and it does crash after a few moments).

**Comment by iondodon** [comment]
Thank you for raising this issue. Yes, indeed I should have mentioned `scrot` in the README. 

I will do my best to fix this issue and I'm happy that this project is useful for other people not just me. 

I did not test with two monitors, I will test this case.

**Comment by iondodon** [comment]
@Cosmic-Goat I fixed some issues and created a new version - v0.2.0 . Could you please download this version and retest the aplication? I added a [i3-switcher-x11-bin-0.2.0-1-x86_64.pkg.tar.zst](https://github.com/iondodon/i3-switcher-x11/releases/download/v.0.2.0/i3-switcher-x11-bin-0.2.0-1-x86_64.pkg.tar.zst) package in the [Releases](https://github.com/iondodon/i3-switcher-x11/releases) page and update the README with installation instructions.

**Comment by Cosmic-Goat** [comment]
Thank you so much for this and for being so kind and helpful! I also really appreciate the creation of an arch package :)

Unfortunately it now gives me the following error when I try to run it:
```
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  33 (X_GrabKey)
  Serial number of failed request:  10
  Current serial number in output stream:  10
```

I wish I had more time at the moment to look into this, but I definitely want to contribute when I get the opportunity! I've asked a friend to try it out and take a look as well, so hopefully they will have some feedback soon.

**Comment by iondodon** [comment]
Thank you for your interest. I think this error is because there is a different application that uses Alt+Tab and locked this binding. You have to unlock it.

**Comment by Cosmic-Goat** [comment]
Ah, you're right! I had Alt+Tab assigned in my i3 config. After removing that it now runs, however the issue of not displaying correctly still persists (it still looks the same as in the screenshot). I tried disabling my second monitor and turning off my compositor but that did not make a difference.

**Comment by iondodon** [comment]
Ok, I will continue the investigation.

**Comment by iondodon** [comment]
@Cosmic-Goat If you run the i3-switcher-x11 app from the command line, do you see any errors there?

**Comment by Cosmic-Goat** [comment]
@iondodon Apologies for the delayed response! I see no output on the command line. Once I have some free time I'll clone the repo and try debugging it myself (if you don't manage to solve it by then).
